/*
 * GENERADO por `scripts/i18n-textos-del-servidor.mjs` desde `i18n/textos/<idioma>/servidor/`: no se edita a mano.
 *
 * Los textos que el servidor escribe sin pasar por la app —el aviso push y la página pública de una publicación—, en
 * cada idioma que los ha traducido. Quien los usa elige la tabla con `tablaDelIdioma` (`./idiomaDelServidor.ts`).
 */

export const AVISOS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "da": {
    "likeTitulo": "Nyt like",
    "likeCuerpo": "{{nombre}} synes godt om dit opslag",
    "comentarioTitulo": "Ny kommentar",
    "comentarioCuerpo": "{{nombre}} kommenterede dit opslag",
    "seguidorTitulo": "Ny følger",
    "seguidorCuerpo": "{{nombre}} er begyndt at følge dig",
    "solicitudTitulo": "Ny ËContact-anmodning",
    "solicitudCuerpo": "{{nombre}} vil tilføje dig til ËContact",
    "aceptadaTitulo": "Ny ËContact",
    "aceptadaCuerpo": "{{nombre}} accepterede din ËContact-anmodning",
    "mencionTitulo": "Du blev nævnt",
    "mencionCuerpo": "{{nombre}} nævnte dig i et opslag",
    "repostTitulo": "Ny deling",
    "repostCuerpo": "{{nombre}} delte dit opslag",
    "respuestaTitulo": "Nyt svar",
    "respuestaCuerpo": "{{nombre}} svarede på din kommentar",
    "mensajeTitulo": "Ny besked",
    "mensajeCuerpo": "{{nombre}} sendte dig en besked",
    "alguien": "Nogen",
    "teEnvioUnMensaje": "Sendte dig en besked",
    "fotoUnica": "Engangsfoto",
    "imagen": "📷 Foto",
    "audio": "🎤 Talebesked"
  },
  "en": {
    "likeTitulo": "New like",
    "likeCuerpo": "{{nombre}} liked your post",
    "comentarioTitulo": "New comment",
    "comentarioCuerpo": "{{nombre}} commented on your post",
    "seguidorTitulo": "New follower",
    "seguidorCuerpo": "{{nombre}} started following you",
    "solicitudTitulo": "New ËContact request",
    "solicitudCuerpo": "{{nombre}} wants to add you to ËContact",
    "aceptadaTitulo": "New ËContact",
    "aceptadaCuerpo": "{{nombre}} accepted your ËContact request",
    "mencionTitulo": "You were mentioned",
    "mencionCuerpo": "{{nombre}} mentioned you in a post",
    "repostTitulo": "New repost",
    "repostCuerpo": "{{nombre}} reposted your post",
    "respuestaTitulo": "New reply",
    "respuestaCuerpo": "{{nombre}} replied to your comment",
    "mensajeTitulo": "New message",
    "mensajeCuerpo": "{{nombre}} sent you a message",
    "alguien": "Someone",
    "teEnvioUnMensaje": "Sent you a message",
    "fotoUnica": "One-time photo",
    "imagen": "📷 Photo",
    "audio": "🎤 Voice message"
  },
  "es": {
    "likeTitulo": "Nuevo like",
    "likeCuerpo": "{{nombre}} le dio like a tu post",
    "comentarioTitulo": "Nuevo comentario",
    "comentarioCuerpo": "{{nombre}} comentó en tu post",
    "seguidorTitulo": "Nuevo seguidor",
    "seguidorCuerpo": "{{nombre}} comenzó a seguirte",
    "solicitudTitulo": "Nueva solicitud de ËContact",
    "solicitudCuerpo": "{{nombre}} quiere agregarte a ËContact",
    "aceptadaTitulo": "Nuevo ËContact",
    "aceptadaCuerpo": "{{nombre}} aceptó tu solicitud de ËContact",
    "mencionTitulo": "Te mencionaron",
    "mencionCuerpo": "{{nombre}} te mencionó en un post",
    "repostTitulo": "Nuevo repost",
    "repostCuerpo": "{{nombre}} reposteó tu publicación",
    "respuestaTitulo": "Nueva respuesta",
    "respuestaCuerpo": "{{nombre}} respondió a tu comentario",
    "mensajeTitulo": "Nuevo mensaje",
    "mensajeCuerpo": "{{nombre}} te envió un mensaje",
    "alguien": "Alguien",
    "teEnvioUnMensaje": "Te envió un mensaje",
    "fotoUnica": "Foto única",
    "imagen": "📷 Imagen",
    "audio": "🎤 Audio"
  }
};

export const PAGINA_PUBLICA: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "da": {
    "codigo": "da",
    "locale": "da_DK",
    "alguien": "Nogen",
    "tituloDelEnlace": "{{nombre}} på Weë",
    "descripcionWeel": "En Weël på Weë.",
    "descripcionVideo": "En video på Weë.",
    "descripcionImagen": "Et billede på Weë.",
    "descripcionEncuesta": "En afstemning på Weë.",
    "descripcionPublicacion": "Et opslag på Weë.",
    "explorar": "Udforsk Weë",
    "privacidad": "Privatliv",
    "terminos": "Vilkår",
    "ayuda": "Hjælp",
    "yaNoDisponible": "Dette opslag er ikke længere tilgængeligt.",
    "noDisponible": "Dette opslag er ikke tilgængeligt.",
    "masEnWee": "og {{contador}} til på Weë",
    "hechoCon": "Lavet med",
    "reposteo": "{{nombre}} delte igen",
    "perfilWee": "Weë-profil",
    "estoEsWee": "Det her er Weë",
    "lema": "Netværket for dem, der skaber med kunstig intelligens. Opdag, lær og del."
  },
  "en": {
    "codigo": "en",
    "locale": "en_US",
    "alguien": "Someone",
    "tituloDelEnlace": "{{nombre}} on Weë",
    "descripcionWeel": "A Weël on Weë.",
    "descripcionVideo": "A video on Weë.",
    "descripcionImagen": "An image on Weë.",
    "descripcionEncuesta": "A poll on Weë.",
    "descripcionPublicacion": "A post on Weë.",
    "explorar": "Explore Weë",
    "privacidad": "Privacy",
    "terminos": "Terms",
    "ayuda": "Help",
    "yaNoDisponible": "This post is no longer available.",
    "noDisponible": "This post isn’t available.",
    "masEnWee": "and {{contador}} more on Weë",
    "hechoCon": "Made with",
    "reposteo": "{{nombre}} reposted",
    "perfilWee": "Weë profile",
    "estoEsWee": "This is Weë",
    "lema": "The network for people who create with Artificial Intelligence. Discover, learn and share."
  },
  "es": {
    "codigo": "es",
    "locale": "es_ES",
    "alguien": "Alguien",
    "tituloDelEnlace": "{{nombre}} en Weë",
    "descripcionWeel": "Un Weël en Weë.",
    "descripcionVideo": "Un video en Weë.",
    "descripcionImagen": "Una imagen en Weë.",
    "descripcionEncuesta": "Una encuesta en Weë.",
    "descripcionPublicacion": "Una publicación en Weë.",
    "explorar": "Explorar Weë",
    "privacidad": "Privacidad",
    "terminos": "Términos",
    "ayuda": "Ayuda",
    "yaNoDisponible": "Esta publicación ya no está disponible.",
    "noDisponible": "Esta publicación no está disponible.",
    "masEnWee": "y {{contador}} más en Weë",
    "hechoCon": "Hecho con",
    "reposteo": "{{nombre}} reposteó",
    "perfilWee": "Perfil Weë",
    "estoEsWee": "Esto es Weë",
    "lema": "La red de quienes crean con Inteligencia Artificial. Descubre, aprende y comparte."
  }
};
